kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "kubakv"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/dimss/kubakv"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "openjdk18-openshift:latest"
  output:
    to:
      kind: "ImageStreamTag"
      name: "kubakv:0.2"